spring:
  application:
    name: peak-kinetics

resend:
  api:
    key: ${RESEND_API_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

google:
  places:
    api:
      key: ${GOOGLE_PLACES_API_KEY}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  forward-headers-strategy: framework
  shutdown: immediate

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

storage:
  upload-dir: uploads

logging:
  level:
    com.peakkineticspt: INFO
    org.springframework.boot.docker.compose: DEBUG
    org.springframework.boot.actuate.autoconfigure: DEBUG